# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('params', '0013_auto_20160615_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.Person')),
            ],
            options={
                'verbose_name_plural': 'Aistencias',
                'verbose_name': 'Aistencia',
            },
        ),
    ]
