# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aistencia',
            new_name='Asistencia',
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
    ]
