# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cobranza',
            new_name='Contabilidad',
        ),
        migrations.AlterModelOptions(
            name='contabilidad',
            options={'verbose_name': 'Contabilidad', 'verbose_name_plural': 'Contabilidades'},
        ),
    ]
