# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_auto_20160616_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('egresos', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Ingresos',
                'verbose_name': 'Ingreso',
            },
        ),
        migrations.RenameModel(
            old_name='Contabilidad',
            new_name='Egreso',
        ),
        migrations.AlterModelOptions(
            name='egreso',
            options={'verbose_name': 'Egreso', 'verbose_name_plural': 'Egresos'},
        ),
    ]
