# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20160616_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egreso',
            old_name='egresos',
            new_name='monto',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='egresos',
            new_name='monto',
        ),
        migrations.RemoveField(
            model_name='egreso',
            name='ingresos',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='ingresos',
        ),
    ]
