# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_cobranza', models.CharField(error_messages={'unique': 'eeeee ee'}, max_length=20, verbose_name='concepto cobranza')),
                ('importe', models.CharField(max_length=50, verbose_name='First name')),
                ('detalle', models.CharField(max_length=50, verbose_name='Last name')),
                ('cobranza_interes', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=50, verbose_name='cobranza interes ')),
                ('fecha_inicio', models.DateField(verbose_name='fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha fin')),
            ],
            options={
                'verbose_name': 'Cobranza',
                'verbose_name_plural': 'Cobranzas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cobranza',
            unique_together=set([('concepto_cobranza', 'importe', 'detalle', 'cobranza_interes', 'fecha_inicio', 'fecha_fin')]),
        ),
    ]
