# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranza',
            name='cobranza_interes',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=50, verbose_name='cobranza interes '),
        ),
        migrations.AlterField(
            model_name='cobranza',
            name='detalle',
            field=models.TextField(max_length=300, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='cobranza',
            name='importe',
            field=models.CharField(max_length=50, verbose_name='Importe'),
        ),
    ]
