# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0003_auto_20160609_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deuda',
            name='cobranza_interes',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=50),
        ),
    ]
