# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('params', '0013_auto_20160615_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('numero_lote', models.CharField(blank=True, max_length=50, null=True)),
                ('ubizacion', models.CharField(max_length=15, unique=True)),
                ('area_terreno', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_construccion', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, default='lotes/default.png', null=True, upload_to='lotes', verbose_name='foto')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.Person')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
