# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad', '0003_auto_20160608_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='module',
            field=models.CharField(choices=[('PRO', 'PROFESIONAL'), ('WEB', 'WEB INFORMATIVA'), ('CONTABILIDAD', 'CONTABILIDAD'), ('COBRANZAS', 'COBRANZAS'), ('SOCIOS', 'SOCIOS'), ('REUNIONES', 'REUNIONES'), ('BACKEND', 'BACKEND')], default='BACKEND', max_length=50, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module',
            field=models.CharField(choices=[('PRO', 'PROFESIONAL'), ('WEB', 'WEB INFORMATIVA'), ('CONTABILIDAD', 'CONTABILIDAD'), ('COBRANZAS', 'COBRANZAS'), ('SOCIOS', 'SOCIOS'), ('REUNIONES', 'REUNIONES'), ('BACKEND', 'BACKEND')], default='BACKEND', max_length=50, verbose_name='Module'),
        ),
    ]
