# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0007_auto_20160609_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='socio',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.Person'),
        ),
    ]
