# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0008_auto_20160613_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('identity_type', 'identity_num'), ('first_name', 'last_name', 'identity_type', 'identity_num')]),
        ),
    ]
