# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0010_auto_20160615_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'TipoUsuario',
                'verbose_name_plural': 'TipoUsuarios',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='tipo_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='params.TipoUsuario'),
            preserve_default=False,
        ),
    ]
