# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0011_auto_20160615_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tipo_usuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
