# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20160608_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'EntidadBancaria',
                'verbose_name_plural': 'EntidadBancarias',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('detalle', models.TextField(blank=True, max_length=300, null=True)),
                ('entidad_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.EntidadBancaria')),
            ],
            options={
                'verbose_name': 'TipoCuenta',
                'verbose_name_plural': 'TipoCuentas',
            },
        ),
        migrations.AlterField(
            model_name='association',
            name='type_a',
            field=models.CharField(choices=[('GOVERMENT', 'GOVIERNO'), ('PRIVATE', 'PRIVADO'), ('MIXED', 'AMBOS'), ('OTHERS', 'OTROS')], default='PRIVATE', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='type_e',
            field=models.CharField(choices=[('GOVERMENT', 'GOVIERNO'), ('PRIVATE', 'PRIVADO'), ('MIXED', 'AMBOS'), ('OTHERS', 'OTROS')], default='PRIVATE', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='cuenta_bancaria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='space.TipoCuenta'),
            preserve_default=False,
        ),
    ]
