# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_auto_20160609_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocuenta',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
