# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_auto_20160609_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocuenta',
            name='entidad_bancaria',
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'TipoCuenta', 'verbose_name_plural': 'TipoCuentas'},
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='detalle',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='entidad_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.EntidadBancaria'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='cuenta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Cuenta'),
        ),
        migrations.DeleteModel(
            name='TipoCuenta',
        ),
    ]
